[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  | bazel-*
  | node_modules
)/
'''

[tool.isort]
profile = "black"
py_version=310
extend_skip_glob = [
  'bazel-*',
]

[tool.ruff]
select = [
  "E",
  "F",
  "I",
  "UP",
  "YTT",
  # "ANN",
  "S",
  "BLE",
  "FBT",
  "B",
  "C4",
  "T10",
  "ISC",
  "ICN",
  "RET",
  "SIM",
  "ARG",
  "ERA",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "PIE",
  "RUF",
]

ignore = ["UP007"]

extend-exclude = [
  "bazel-*",
]
